### ISSUE TITLE
Set up Kanban board

### ISSUE THREAD

**Issue by gtekle** [gtekle/mmo-games#21]
https://github.com/gtekle/mmo-games/projects/1

**NB:-** There are two team members in this project.

**Comment by TedLivist** [comment]
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @gtekle,

Good job so far!
✔️ Kanban columns are correctly set up
✔️ Cards are complete.
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**
- [ ] All your task cards are missing assignees (see example image). Kindly add them. Be sure to add the other team member as a **`collaborator`** so you can assign tasks to him/her. Determine who would be **Student A** and who will be **Student B**

  Your Card | Template
  :---:|:---:
  ![tekle-card](https://user-images.githubusercontent.com/36542986/151823213-73e87458-83cb-46a2-9a09-2b862ea2c404.jpg) | ![tekle-corr](https://user-images.githubusercontent.com/36542986/151823228-ceff115e-2819-4f13-ab2a-36e4465cf53b.jpg)

Feel free to leave any questions or comments in the Issue if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by gtekle** [comment]
Hi @TedLivist,
Thank you very much for the feedback. We will definitely add the assignee.
thanks again

**Comment by elyor-doniyorov** [comment]
Hi @gtekle and @Beardless-sheik, 

Your Kanban board is complete!  There is nothing else to say other than... you can start working on the tasks :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by gtekle** [comment]
Hi @elyor-doniyorov 
Thank you very much.
